name: Selenium IDE CI
on:
  push: 
      branches:
	 - main
  pull_request:
      branches:
         - main
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkkout@v3

  - name: Set up .Net
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: "6.0.x"

   - name: Install dependencies
     uses: dotnet restore  

   - name: Build
     uses: dotnet build --no-restore

   - name: Run tests
     uses: dotnet test --verbosity normal
	